---
title: "collecting_enviromental_data"
author: "Katie Wang"
date: "2024-07-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, messages = FALSE)
```

```{r}
#loading in the packages :D
library(tidyverse)
library(sdmpredictors)
library(raster)
library(sp)
library(sf)
library(here)
library(stringr)
library(dbplyr)
```

```{r}
#listing all of the different variables 
library(biooracler)

dataset <- list_layers()
dataset
```

-----------------------------------------------------------------------------
#Loading in everything else

```{r}
latitude = c(-89.975, 89.975)
longitude = c(-179.975, 179.975)
constraints = list(latitude, longitude)
names(constraints) = c("latitude", "longitude")
```

```{r}
info_layer("thetao_ssp119_2020_2100_depthmean")
```

```{r}
#importing the mean ocean temperature
dataset_id1 <- "thetao_baseline_2000_2019_depthmean"
variables = c("thetao_mean") #choosing the mean of the mean temperature 
mean_ocean_temp <- download_layers(dataset_id1, variables, constraints)
```

```{r}
#importing the mean salinity
dataset_id3<- "so_baseline_2000_2019_depthmean"
variables = c("so_mean") #choosing the mean of salinity
salinity <- download_layers(dataset_id3, variables, constraints)
```

```{r}
#importing the mean TotalPhytoplankton
dataset_id4 <- "phyc_baseline_2000_2020_depthmean"
variables = c("phyc_mean") #choosing the mean of TotalPhytoplankton <- can be rep of primary productivity
totalphytoplankton <- download_layers(dataset_id4, variables, constraints)
```

```{r}
#importing the mean pH
dataset_id5 <- "ph_baseline_2000_2018_depthmean"
variables = c("ph_mean") #choosing the mean of pH
ph <- download_layers(dataset_id5, variables, constraints)
```

```{r}
#importing the mean chlorophyll
dataset_id6 <- "chl_baseline_2000_2018_depthmean"
variables = c("chl_mean") #choosing the mean of chlorophyll
chlorophyll <- download_layers(dataset_id6, variables, constraints)
```

```{r}
#importing the MixedLayerDepth
dataset_id7 <- "mlotst_baseline_2000_2019_depthsurf"
variables = c("mlotst_mean") #choosing the mean of MixedLayerDepth
mixedlayerdepth <- download_layers(dataset_id7, variables, constraints)
```

Can plot(variable) <- to see the current data

-----------------------------------------------------------------------------
#Reading in Manta Data + doing some changes

```{r}
#reading the manta data (model data)
manta_data <- st_read("Data/model_data.csv")
```

```{r}
#removing the c() around the coordinates
manta_data <- manta_data %>%
  mutate(
    geometry = str_replace(geometry, "c\\(", "") %>%
      str_replace_all("\\)", ""),
    geometry2 = str_replace(geometry2, "c\\(", "") %>%
      str_replace_all("\\)", "")
  )
```

```{r}
manta_data <- manta_data %>%
  rename(
    longitude = geometry,
    latitude = geometry2
  )
```

```{r}
manta_data_sf <- st_as_sf(manta_data, coords = c("longitude", "latitude"), crs = "EPSG:4326") 
```

```{r}
coords <- st_coordinates(manta_data_sf)

# Add longitude and latitude to the data frame
manta_data_sf <- manta_data_sf %>%
  mutate(
    longitude = coords[, 1],
    latitude = coords[, 2]
  )

# Print the updated data frame
print(manta_data_sf)
```



-----------------------------------------------------------------------------
#Mean temperature
```{r}
#setting the max ocean temp crs to be the same
mean_temp <- terra::project(mean_ocean_temp,
                                 crs(manta_data_sf))
terra::crop(mean_ocean_temp, manta_data_sf)
temp = terra::extract(x = mean_ocean_temp,y = manta_data_sf)
```

```{r}
# selecting just the 2010 - 2019 column and renaming it to mean_temp 
temp_final <- temp %>%
  dplyr::select("thetao_mean_2") %>% 
  rename("mean_temp" = "thetao_mean_2")
```

-----------------------------------------------------------------------------
#Salinity
```{r}
mean_salinity <- terra::project(salinity,
                                 crs(manta_data_sf))
terra::crop(salinity, manta_data_sf)
salinity = terra::extract(x = salinity,y = manta_data_sf)
```

```{r}
# selecting just the 2010 - 2019 column and renaming it to mean_temp 
salinity_final <- salinity %>%
  dplyr::select("so_mean_2") %>% 
  rename("mean_salinity" = "so_mean_2")
```

-----------------------------------------------------------------------------
#Mean phytoplankton 
```{r}
mean_totalphytoplankton <- terra::project(totalphytoplankton,
                                 crs(manta_data_sf))
terra::crop(totalphytoplankton, manta_data_sf)
totalphytoplankton = terra::extract(x = totalphytoplankton,y = manta_data_sf)
```

```{r}
# selecting just the 2010 - 2019 column and renaming it to mean_temp 
totalphytoplankton_final <- totalphytoplankton %>%
  dplyr::select("phyc_mean_2") %>% 
  rename("mean_total_phytoplankton" = "phyc_mean_2")
```

-----------------------------------------------------------------------------
#Mean pH
```{r}
mean_ph <- terra::project(ph,
                          crs(manta_data_sf))
terra::crop(ph, manta_data_sf)
ph = terra::extract(x = ph,y = manta_data_sf)
```

```{r}
ph_final <- ph %>%
  dplyr::select("ph_mean_2") %>% 
  rename("mean_ph" = "ph_mean_2")
```

-----------------------------------------------------------------------------
#Mean chlorophyll
```{r}
mean_chlorophyll <- terra::project(chlorophyll,
                                 crs(manta_data_sf))
terra::crop(chlorophyll, manta_data_sf)
chlorophyll = terra::extract(x = chlorophyll,y = manta_data_sf)
```

```{r}
# selecting just the 2010 - 2019 column and renaming it to mean_temp 
chlorophyll_final <- chlorophyll %>%
   dplyr::select("chl_mean_2") %>% 
  rename("mean_chlorophyll" = "chl_mean_2")
```

-----------------------------------------------------------------------------
#Mean Mixed Layer Depth
```{r}
mean_mixedlayerdepth <- terra::project(mixedlayerdepth,
                                 crs(manta_data_sf))
terra::crop(mixedlayerdepth, manta_data_sf)
mixedlayerdepth = terra::extract(x = mixedlayerdepth,y = manta_data_sf)

print(mixedlayerdepth)
```

```{r}
# selecting just the 2010 - 2019 column and renaming it to mean_temp 
mixedlayerdepth_final <- mixedlayerdepth %>%
   dplyr::select("mlotst_mean_2") %>% 
  rename("mean_MixedLayerDepth" = "mlotst_mean_2")
```

-----------------------------------------------------------------------------
#Writing to the csv
  
```{r}
write.csv(temp_final, "Data/temp_final2.csv", row.names = FALSE)
```

```{r}
write.csv(salinity_final, "Data/salinity_final2.csv", row.names = FALSE)
```

```{r}
write.csv(totalphytoplankton_final, "Data/totalphytoplankton_final2.csv", row.names = FALSE)
```

```{r}
write.csv(ph_final, "Data/ph_final2.csv", row.names = FALSE)
```

```{r}
write.csv(chlorophyll_final, "Data/chlorophyll_final2.csv", row.names = FALSE)
```

```{r}
write.csv(mixedlayerdepth_final, "Data/MixedLayerDepth_final2.csv", row.names = FALSE)
```

```{r}
manta_data_sf_drop2 <- manta_data_sf %>%
  dplyr::select("occurrenceStatus", "longitude", "latitude") %>% 
  rename("occurrences" = "occurrenceStatus")

```

#don't even know how this code works but it dropped geometry
```{r}
library(dplyr)
library(sf)

# Convert to data frame to drop geometry column
manta_data_sf_drop2 <- as.data.frame(manta_data_sf) %>%
  dplyr::select(occurrenceStatus, longitude, latitude) %>%
  rename(occurrences = occurrenceStatus)

# Saving the modified data frame to a CSV file
write.csv(manta_data_sf_drop2, "Data/manta_final.csv", row.names = FALSE)
```


#IDK what is this 
```{r}
temp_sf <- st_as_sf(temp, coords = c("longitude", "latitude"), crs = 4326)

p1 <- ggplot(temp_sf) +
  geom_sf(aes(fill = thetao_mean_1)) +
  scale_fill_viridis_c(name = "Mean Temperature (°C)") +
  labs(x = "Longitude", y = "Latitude", title = "Mean Temperature in Each MPA",
       fill = "Mean Temperature") +
  theme_minimal()

# Display the plot
print(p1)
```

```{r}
glm(formula = present ~ tmin + precip, family = binomial(link = "logit"), 
     data = hooded_warb_data)
```