---
title: "Combining csv files"
author: "Ivy Zhou"
date: "2024-07-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, messages = FALSE)
library(tidyverse)
library(here)
library(readr)
library(sf)
```

```{r}
temp_final <- read.csv("Data/temp_final.csv", header = TRUE)
```

```{r}
salinity_final <- read.csv("Data/salinity_final.csv", header = TRUE)
```

```{r}
totalphytoplankton_final <- read.csv("Data/totalphytoplankton_final.csv", header = TRUE)
```

```{r}
ph_final <- read.csv("Data/ph_final.csv", header = TRUE)
```

```{r}
chlorophyll_final <- read.csv("Data/chlorophyll_final.csv", header = TRUE)
```

```{r}
mixedlayerdepth_final <-read.csv("Data/mixedlayerdepth_final.csv", header = TRUE)
```

```{r}
primaryproductivity_final <-read.csv("Data/primaryproductivity_final.csv", header = TRUE)
```

```{r}
manta_data_sf <- read.csv("Data/manta_final.csv") 
#manta_complete %>% 
  #slice(1:19485)
#st_as_sf(model_data)
```


```{r}
combined_data <- cbind(temp_final, mixedlayerdepth_final, primaryproductivity_final, salinity_final, totalphytoplankton_final, ph_final, chlorophyll_final, manta_data_sf)
```


```{r}
combined_data <- na.omit(combined_data)

write.csv(combined_data, "Data/combined_data_final.csv", row.names = FALSE)
```
