---
title: "test"
author: "Ivy Zhou"
date: "2024-07-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
 #install.packages("spDataLarge", repos = "https://geocompr.r-universe.dev")

library(sf)
library(terra)
library(spData)
library(spDataLarge)
library(tidyverse)
library(stars)
library(patchwork)
```

```{r}
ch_mean = alpha21 = -0.8 %>% 
  summarize(mean_latitude = mean(decimal_latitude, na.rm = TRUE)) %>% 
  full_join(ch) %>% 
  st_as_sf() #turning data that you created into an sf object so you can use it to plot a map
```

```{r}
Manta_occurrence_shp = plot_locations_Manta %>% 
  group_by(ID) %>% 
  summarize(mean_srtm = mean(srtm, na.rm = TRUE)) %>% 
  full_join(ch) %>% 
  st_as_sf() #turning data that you created into an sf object so you can use it to plot a map
```


### Raster and Vector Operations


####read_sf reads shape files, while rast() reads raster files.

### Maps in R

## plotting vector data
```{r}
plot_locations_Manta <- st_as_sf(Manta_complete, coords = c(2, 1)) 

Manta_crs <- plot_locations_Manta %>% 
  st_set_crs("EPSG:4326")
 
#set crs to WGS84
```

```{r}
st_crs(Manta_crs)
```
```{r}
st_write(Manta_crs, "Data/manta_crs.shp")
```


```{r}
ggplot() +
  geom_sf(data = plot_locations_Manta, color = "green") + #has points according to lat and lon
  #geom_sf(data = ch, fill = "transparent") + #creates grid
  theme_bw() 
  #theme(panel.grid = element_blank()) #remove line from standard ggplot graph
```
```{r}
library(raster)
library(rasterVis)

csv_path <- "file.csv"
csv_file <- paste(csv_path, sep="")
temp <- read.csv(csv_file) # takes a while
str(temp)
temp_coords <- cbind(temp$lon, temp$lat)
temp_pts <- SpatialPointsDataFrame(coords=temp_coords, 
data=data.frame(temp$temp))
names(temp_pts) <- "temp"

cell_size <- 0.75
lon_min <- -125.0; lon_max <- -65.0; lat_min <- 25.5; lat_max <- 50.5
ncols <- ((lon_max - lon_min)/cell_size)+1; nrows <- ((lat_max - lat_min)/cell_size)+1 
gridtemp <- raster(nrows=nrows, ncols=ncols, xmn=lon_min, xmx=lon_max, ymn=lat_min, ymx=lat_max, res=cell_size, crs="+proj=longlat +datum=WGS84")
gridtemp

us_fire <- rasterize(temp_coords, gridtemp, fun=mean)
us_fire

plot(us_fire, col=brewer.pal(9,"PuBuGn"), sub="CSV2RASTER")
```

